[network]
ip = "0.0.0.0"
domain = "localhost"
node_id = 1
server_port = 8080
name = "primary-node"
node_endpoints = ["127.0.0.1:8081", "127.0.0.1:8082"]
node_dns_names = ["primary-node", "secondary-node-1", "secondary-node-2"]
node_id_discovery_sleep = 3
node_id_discovery_retries = 5

[protocol]
max_message_size = 65536
send_timeout_ms = 300
receive_message_timeout_ms = 2000

[http]
compression = true
compression_lvl = 3
port = 4443
load_rate_limit = 60
leader_rate_limit = 10
add_task_rate_limit = 100
request_size_limit = 1572864
wss_bittensor = "wss://entrypoint-finney.opentensor.ai:443"
wss_max_message_size = 2097152
wss_max_connect_time = 10
signature_freshness_threshold = 30
subnet_number = 17
subnet_poll_interval_sec = 3600
max_task_queue_len = 10000

[db]
host = ""
port = 5432
user = ""
password = ""
db = ""
ca_path = ""
api_keys_update_interval = 120

[cert]
dangerous_skip_verification = true
cert_file_path = ""
key_file_path = ""

[basic]
max_restart_attempts = 2
update_gateway_info_ms = 1000
unique_validators_per_task = 3

[log]
path = "./logs/gateway.log"
level = "Info"

[raft]
cluster_name = "gateway_cluster"
election_timeout_min = 1500
election_timeout_max = 3000
heartbeat_interval = 500
max_payload_entries = 300
replication_lag_threshold = 500
snapshot_logs_since_last = 1000
snapshot_max_chunk_size = 128000
max_in_snapshot_log_to_keep = 2000
