[network]
ip = "0.0.0.0"
domain = ""
node_id = 1
server_port = 8080
name = "primary-node"
node_endpoints = ["127.0.0.1:8081", "127.0.0.1:8082"]
node_ids = [2,3]
node_dns_names = ["primary-node", "secondary-node-1", "secondary-node-2"]

[http]
port = 4443
load_rate_limit = 10
add_task_rate_limit = 100
request_size_limit = 1572864

[cert]
cert_file_path = "/etc/letsencrypt/live/gateway.404.xyz/fullchain.pem"
key_file_path = "/etc/letsencrypt/live/gateway.404.xyz/privkey.pem"

[basic]
max_restart_attempts = 2

[log]
path = "./logs/gateway.log"
level = "Info"

[raft]
cluster_name = "gateway_cluster"
election_timeout_min = 1500
election_timeout_max = 3000
heartbeat_interval = 500
max_payload_entries = 300
replication_lag_threshold = 500
snapshot_logs_since_last = 1000
snapshot_max_chunk_size = 128000
max_in_snapshot_log_to_keep = 2000
