[network]
node_id = 3
ip = "172.25.0.4"
domain = "node-3"
server_port = 9090
name = "node-3"
node_endpoints = ["172.25.0.2:9090", "172.25.0.3:9090"]
node_ids = [1,2]
node_dns_names = ["node-1", "node-2"]

[protocol]
max_message_size = 65536
send_timeout_ms = 300
receive_message_timeout_ms = 2000

[http]
compression = true
compression_lvl = 3
port = 4443
load_rate_limit = 10
leader_rate_limit = 10
add_task_rate_limit = 100
request_size_limit = 1572864
bittensor_wss = "wss://entrypoint-finney.opentensor.ai:443"
signature_freshness_threshold = 30

[cert]
dangerous_skip_verification = true
cert_file_path = "/etc/certs/cert.pem"
key_file_path = "/etc/certs/key.pem"

[basic]
max_restart_attempts = 2
update_gateway_info_ms = 1000
unique_validators_per_task = 3

[log]
path = "./logs/gateway.log"
level = "Info"

[raft]
cluster_name = "gateway_cluster"
election_timeout_min = 5000
election_timeout_max = 10000
heartbeat_interval = 500
max_payload_entries = 300
replication_lag_threshold = 500
snapshot_logs_since_last = 1000
snapshot_max_chunk_size = 128000
max_in_snapshot_log_to_keep = 2000
