[network]
node_id = 1
bind_ip = "172.25.0.2"
external_ip = "172.25.0.2"
domain = "node-1"
server_port = 9090
name = "node-1"
node_dns_names = []
node_id_discovery_sleep = 3
node_id_discovery_retries = 5

[http]
compression = true
compression_lvl = 3
port = 4443
basic_rate_limit = 30
write_rate_limit = 180
update_key_rate_limit = 10
add_task_basic_per_ip_rate_limit = 50
add_task_generic_global_hourly_rate_limit = 40
add_task_generic_per_ip_hourly_rate_limit = 5
add_task_user_id_global_hourly_rate_limit = 60
add_task_user_id_per_user_hourly_rate_limit = 5
add_task_size_limit = 2097152
load_rate_limit = 60
leader_rate_limit = 10
metric_rate_limit = 5
get_status_rate_limit = 600
request_size_limit = 4096
request_file_size_limit = 31457280
raft_write_size_limit = 262144
add_result_rate_limit = 300
wss_bittensor = "wss://entrypoint-finney.opentensor.ai:443"
wss_max_message_size = 2097152
wss_max_connect_time = 10
signature_freshness_threshold = 30
subnet_number = 17
subnet_poll_interval_sec = 3600
max_task_queue_len = 500
admin_key = "b6c8597a-00e9-493a-b6cd-5dfc7244d46b"
generic_key = "518d5860-589f-4625-be7c-285d5b669ee2"
api_key_secret = "CHANGE_ME_IN_PRODUCTION_58392047"
post_timeout_sec = 2
forward_timeout_sec = 3
get_timeout_sec = 2
max_idle_timeout_sec = 4
keep_alive_interval_sec = 1
add_task_whitelist = ["172.25.0.1"]
company_rate_limiter_max_capacity = 4096

[db]
host = "db"
port = 5432
user = "postgres"
password = "api_keys_!54321"
db = "api_keys_db"
sslcert = "/certs/client.crt"
sslkey = "/certs/client.key"
sslrootcert = "/certs/ca.crt"
api_keys_update_interval = 120
keys_cache_ttl_sec = 43200
keys_cache_initial_capacity = 16000
keys_cache_max_capacity = 32000
deleted_keys_ttl_minutes = 60

[cert]
dangerous_skip_verification = true
cert_file_path = "/etc/certs/cert.pem"
key_file_path = "/etc/certs/key.pem"

[basic]
max_restart_attempts = 2
update_gateway_info_ms = 1000
unique_validators_per_task = 3
taskmanager_initial_capacity = 1024
taskmanager_cleanup_interval = 30
taskmanager_result_lifetime = 2000
taskqueue_cleanup_interval = 1
taskqueue_task_ttl = 1800

[log]
path = "./logs/gateway.log"
level = "Info"

[rclient]
max_idle_timeout_sec = 4
keep_alive_interval_sec = 1

[rserver]
max_message_size = 262144
max_recv_buffer_size = 8192
receive_message_timeout_ms = 5000
max_idle_timeout_sec = 4
keep_alive_interval_sec = 1

[raft]
cluster_name = "gateway_cluster"
election_timeout_min = 5000
election_timeout_max = 10000
heartbeat_interval = 500
max_payload_entries = 100
replication_lag_threshold = 1200
snapshot_logs_since_last = 1000
snapshot_max_chunk_size = 131072
max_in_snapshot_log_to_keep = 1000

[prompt]
min_len = 3
max_len = 384
allowed_pattern = "^[A-Za-z0-9 .,'():;/?!+%-]+$"

[image]
max_width = 1024
max_height = 1024
max_size_bytes = 2097152  # 2MB
allowed_formats = ["png", "jpg", "webp"]
