[network]
node_id = 3
ip = "172.25.0.4"
domain = "node-3"
server_port = 9090
name = "node-3"
node_endpoints = ["172.25.0.2:9090", "172.25.0.3:9090"]
node_dns_names = ["node-1", "node-2"]
node_id_discovery_sleep = 3
node_id_discovery_retries = 5

[protocol]
max_message_size = 65536
send_timeout_ms = 300
receive_message_timeout_ms = 2000

[http]
compression = true
compression_lvl = 3
port = 4443
basic_rate_limit = 30
write_rate_limit = 10
load_rate_limit = 60
leader_rate_limit = 10
add_task_rate_limit = 100
request_size_limit = 1572864
wss_bittensor = "wss://entrypoint-finney.opentensor.ai:443"
wss_max_message_size = 2097152
wss_max_connect_time = 10
signature_freshness_threshold = 30
subnet_number = 17
subnet_poll_interval_sec = 3600
max_task_queue_len = 5000
admin_key = "b6c8597a-00e9-493a-b6cd-5dfc7244d46b"

[db]
host = "db"
port = 5432
user = "postgres"
password = "api_keys_!54321"
db = "api_keys_db"
ca_path = "/certs/ca.crt"
api_keys_update_interval = 120

[cert]
dangerous_skip_verification = true
cert_file_path = "/etc/certs/cert.pem"
key_file_path = "/etc/certs/key.pem"

[basic]
max_restart_attempts = 2
update_gateway_info_ms = 1000
unique_validators_per_task = 3
taskmanager_initial_capacity = 1024
taskmanager_cleanup_interval = 30
taskmanager_result_lifetime = 300

[log]
path = "./logs/gateway.log"
level = "Info"

[raft]
cluster_name = "gateway_cluster"
election_timeout_min = 5000
election_timeout_max = 10000
heartbeat_interval = 500
max_payload_entries = 300
replication_lag_threshold = 500
snapshot_logs_since_last = 1000
snapshot_max_chunk_size = 128000
max_in_snapshot_log_to_keep = 2000
