[network]
node_id = 3
ip = "172.25.0.4"
server_port = 9090
name = "node-3"
node_endpoints = ["172.25.0.2:9090", "172.25.0.3:9090"]
node_ids = [1,2]
node_dns_names = ["node-1", "node-2"]

[basic]
max_restart_attempts = 2

[log]
path = "./logs/gateway.log"
level = "Info"

[raft]
cluster_name = "gateway_cluster"
election_timeout_min = 5000
election_timeout_max = 10000
heartbeat_interval = 500
max_payload_entries = 300
replication_lag_threshold = 500
snapshot_logs_since_last = 1000
snapshot_max_chunk_size = 128000
max_in_snapshot_log_to_keep = 2000
