[network]
node_id = 1
bind_ip = "172.25.0.2"
external_ip = "172.25.0.2"
domain = "node-1"
server_port = 9090
name = "node-1"
node_endpoints = ["172.25.0.3:9090", "172.25.0.4:9090"]
node_dns_names = ["node-1", "node-2"]
node_id_discovery_sleep = 3
node_id_discovery_retries = 5

[http]
compression = true
compression_lvl = 3
port = 4443
basic_rate_limit = 30
write_rate_limit = 180
update_key_rate_limit = 10
generic_key_rate_limit = 2
load_rate_limit = 60
leader_rate_limit = 10
add_task_rate_limit = 8
metric_rate_limit = 5
request_size_limit = 102400
request_file_size_limit = 31457280
wss_bittensor = "wss://entrypoint-finney.opentensor.ai:443"
wss_max_message_size = 2097152
wss_max_connect_time = 10
signature_freshness_threshold = 30
subnet_number = 17
subnet_poll_interval_sec = 3600
max_task_queue_len = 500
admin_key = "b6c8597a-00e9-493a-b6cd-5dfc7244d46b"
post_timeout_sec = 2
get_timeout_sec = 2
max_idle_timeout_sec = 4
keep_alive_interval_sec = 1

[db]
host = "db"
port = 5432
user = "postgres"
password = "api_keys_!54321"
db = "api_keys_db"
ca_path = "/certs/ca.crt"
api_keys_update_interval = 120

[cert]
dangerous_skip_verification = true
cert_file_path = "/etc/certs/cert.pem"
key_file_path = "/etc/certs/key.pem"

[basic]
max_restart_attempts = 2
update_gateway_info_ms = 1000
unique_validators_per_task = 3
taskmanager_initial_capacity = 1024
taskmanager_cleanup_interval = 30
taskmanager_result_lifetime = 2000
taskqueue_cleanup_interval = 1
taskqueue_task_ttl = 1800

[log]
path = "./logs/gateway.log"
level = "Info"

[rclient]
max_idle_timeout_sec = 4
keep_alive_interval_sec = 1

[rserver]
max_message_size = 262144
receive_message_timeout_ms = 5000
max_idle_timeout_sec = 4
keep_alive_interval_sec = 1

[raft]
cluster_name = "gateway_cluster"
election_timeout_min = 5000
election_timeout_max = 10000
heartbeat_interval = 500
max_payload_entries = 100
replication_lag_threshold = 1200
snapshot_logs_since_last = 1000
snapshot_max_chunk_size = 131072
max_in_snapshot_log_to_keep = 1000
