services:
  cert-gen:
    image: alpine/openssl
    entrypoint: []
    command: >
      sh -c "if [ ! -f /certs/server.crt ]; then
              echo 'Generating CA certificate...';
              openssl genrsa -out /certs/ca.key 2048;
              openssl req -new -x509 -key /certs/ca.key -out /certs/ca.crt -days 365 -subj '/CN=PostgreSQL CA';

              echo 'Generating server certificate...';
              openssl genrsa -out /certs/server.key 2048;
              openssl req -new -key /certs/server.key -out /certs/server.csr -subj '/CN=db';
              echo '[extensions]' > /tmp/server.cnf;
              echo 'subjectAltName = DNS:db,DNS:localhost,IP:127.0.0.1,IP:172.25.0.5' >> /tmp/server.cnf;
              openssl x509 -req -in /certs/server.csr -CA /certs/ca.crt -CAkey /certs/ca.key -CAcreateserial -out /certs/server.crt -days 365 -extfile /tmp/server.cnf -extensions extensions;

              echo 'Generating client certificate...';
              openssl genrsa -out /certs/client.key 2048;
              openssl req -new -key /certs/client.key -out /certs/client.csr -subj '/CN=postgres';
              openssl x509 -req -in /certs/client.csr -CA /certs/ca.crt -CAkey /certs/ca.key -CAcreateserial -out /certs/client.crt -days 365;

              echo 'Setting file permissions...';
              chown 999:999 /certs/server.key /certs/server.crt /certs/ca.crt /certs/client.key /certs/client.crt;
              chmod 600 /certs/server.key /certs/client.key;
              chmod 644 /certs/server.crt /certs/ca.crt /certs/client.crt;

              echo 'Certificates generated successfully';
            fi"
    volumes:
      - certs:/certs
    restart: "no"

  db:
    image: postgres:17
    depends_on:
      cert-gen:
        condition: service_completed_successfully
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: api_keys_!54321
      POSTGRES_DB: api_keys_db
    ports:
      - "127.0.0.1:5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
      - ./init-scripts:/docker-entrypoint-initdb.d
      - certs:/certs
      - ./custom-postgresql.conf:/etc/postgresql/postgresql.conf
    command: ["-c", "config_file=/etc/postgresql/postgresql.conf"]
    networks:
      my_network:
        ipv4_address: 172.25.0.5
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -d $$POSTGRES_DB -U $$POSTGRES_USER"]
      interval: 5s
      timeout: 10s
      retries: 3
      start_period: 5s

  node-1:
    image: gateway:latest
    container_name: node-1
    environment:
      - GATEWAY_CONFIG=/usr/local/bin/config.toml
    volumes:
      - ./config/config-single.toml:/usr/local/bin/config.toml
      - certs:/certs
      - node_data:/var/lib/gateway
    networks:
      my_network:
        ipv4_address: 172.25.0.2
    depends_on:
      cert-gen:
        condition: service_completed_successfully
      db:
        condition: service_healthy
    expose:
      - "9090"
      - "9091"
    command: ["/usr/local/bin/gateway", "--mode", "single"]

networks:
  my_network:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: "172.25.0.0/16"

volumes:
  db_data:
  certs:
  node_data:
